version: "3"
services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile
    image: airflowimage
    container_name: gemstone-prediction-airflow
    ports:
      - "8080:8080"
    
